import javax.swing.*;
import javax.swing.tree.*;

/**
 * <p>Title: Java BonjourBrowser</p>
 *
 * <p>Description: </p>
 * An application like Bonjour Browser is necessary to view the services that are present and being announced in a network where devices are Bonjour-capable. While Bonjour Browser does a very good job on the Mac OS X platform, we will need an application that can work similarly, display all services and run on several platforms. Hence it was necessary to build a tool like Bonjour Browser in Java that could run on multiple platforms.<br>
 * A tool like Bonjour Browser is especially helpful while troubleshooting service discovery in the IRT Lab's 7DS research, since the project involves mobile disconnected networks where devices are often very transient and services are announced and disappear shortly afterwards. .

 * @author Denis Abramov
 * @author Myounghwan Lee
 * @version 1.0
 */

import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.event.*;

/**
  * Main class for GUI components/events.<br>
*/

public class BonjourBrowser
    extends JFrame {

/**
  * Constructs a new BonjourBrowser.<br>
  * Sets the GUI property.
*/

  public BonjourBrowser() {
    try {
      jbInit();
    }
    catch (Exception ex) {
      ex.printStackTrace();
    }
  }

  private void jbInit() throws Exception {
    this.getContentPane().setLayout(gridBagLayout1);
    reloadServicesBtn.setBorder(BorderFactory.createRaisedBevelBorder());
    reloadServicesBtn.setText("Reload Services");
    reloadServicesBtn.addActionListener(new
        BonjourBrowser_reloadServicesBtn_actionAdapter(this));
    this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    this.setTitle("Bonjour Service Browser");
    tree.setRootVisible(false);
    tree.addTreeExpansionListener(new BonjourBrowser_tree_treeExpansionAdapter(this));
    this.getContentPane().add(jScrollPane1,             new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0
            ,GridBagConstraints.NORTH, GridBagConstraints.BOTH, new Insets(0, 0, 0, 0), 500, 600));
    this.getContentPane().add(reloadServicesBtn,
                                       new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0
            ,GridBagConstraints.SOUTH, GridBagConstraints.BOTH, new Insets(20, 0, 0, 0), 0, 15));
    jScrollPane1.getViewport().add(tree, null);
  }
/**
 * JTree for the browser.
*/
  public JTree tree = new JTree();
/**
 * JButton for the reload services button.
*/
  public JButton reloadServicesBtn = new JButton();
  GridBagLayout gridBagLayout1 = new GridBagLayout();
/**
   * BonjourBrowserImpl instance for the browser.
*/
  public BonjourBrowserImpl _bonjourBrowserImpl;
  JScrollPane jScrollPane1 = new JScrollPane();

/**
  * Main method of this class.<br>
  * Creates {@link BonjourBrowser} class<br>
  * Implements BonjourBrowser by {@link BonjourBrowserImpl} class.<br>
*/
  public static void main(String args[]) {
    try {
      BonjourBrowser browser = new BonjourBrowser();
      browser.addWindowListener(new WindowAdapter() {
        public void windowClosing(WindowEvent e) {
          System.exit(0);
        }
      });

      browser._bonjourBrowserImpl = new BonjourBrowserImpl(browser);
      browser.setSize(600, 720);
      browser.reloadServicesBtn_actionPerformed(null);
      browser.show();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

/**
  * Performs the action of reloadServices Botton.<br>
  * Resets the tree and calls the {@link BonjourBrowserMultiServiceListener} class.<br>
  * @param actionEvent  the event generated by the reloadServicesBtn<br>
*/

  public void reloadServicesBtn_actionPerformed(ActionEvent actionEvent) {
    DefaultMutableTreeNode root_node = null;
    root_node = new DefaultMutableTreeNode("");
    DefaultTreeModel treeModel = new DefaultTreeModel(root_node);
    tree.setModel(treeModel);

    try {
      BonjourBrowserMultiServiceListener listener = new BonjourBrowserMultiServiceListener(_bonjourBrowserImpl);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  void tree_treeExpanded(TreeExpansionEvent e) {
    TreePath path = e.getPath();
    if (path.getPathCount() != 3 || this._bonjourBrowserImpl._ignore_tree_expansion)
      return;

    DefaultMutableTreeNode domain = (DefaultMutableTreeNode) path.getPathComponent(1);
    DefaultMutableTreeNode regType = (DefaultMutableTreeNode) path.getPathComponent(2);
    this._bonjourBrowserImpl.subscribe((String) domain.getUserObject(), (String) regType.getUserObject() );
  }
}

class BonjourBrowser_reloadServicesBtn_actionAdapter
    implements ActionListener {
  private BonjourBrowser adaptee;
  BonjourBrowser_reloadServicesBtn_actionAdapter(BonjourBrowser adaptee) {
    this.adaptee = adaptee;
  }

  public void actionPerformed(ActionEvent actionEvent) {
    adaptee.reloadServicesBtn_actionPerformed(actionEvent);
  }
}

class BonjourBrowser_tree_treeExpansionAdapter implements javax.swing.event.TreeExpansionListener {
  BonjourBrowser adaptee;

  BonjourBrowser_tree_treeExpansionAdapter(BonjourBrowser adaptee) {
    this.adaptee = adaptee;
  }
  public void treeCollapsed(TreeExpansionEvent e) {
  }
  public void treeExpanded(TreeExpansionEvent e) {
    adaptee.tree_treeExpanded(e);
  }
}
